In [ ]:
import pandas as pd
import random

In [3]:
import pandas as pd

df = pd.read_csv("/content/C:\Users\Laptop house\Downloads\IRIS.csv")
print(df.head())

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \UXXXXXXXX escape (1217291801.py, line 3)

In [4]:
from google.colab import files

uploaded = files.upload()

Saving IRIS.csv to IRIS.csv

In [5]:
import pandas as pd

df = pd.read_csv("IRIS.csv")

print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

df.info()

Shape: (150, 5)
Columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
df.shape

(150, 5)

In [8]:
df.columns.tolist()

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
print(df.tail())

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [13]:
print(df.columns.tolist())

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [15]:
X = df.drop("species", axis=1)

print(X.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
y = df["species"]

print(y.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [17]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (150, 4)
y shape: (150,)

In [18]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training features: (120, 4)
Testing features: (30, 4)
Training labels: (120,)
Testing labels: (30,)

In [19]:

from sklearn.tree import DecisionTreeClassifier

# Create the model
model = DecisionTreeClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [20]:

# Predict flower species using testing data
y_pred = model.predict(X_test)

print("Actual species:")
print(y_test.head(10).to_list())

print("\nPredicted species:")
print(y_pred[:10])

Actual species:
['Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor']

Predicted species:
['Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor']

In [21]:

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Model accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

Model accuracy: 0.9333333333333333
Accuracy percentage: 93.33333333333333 %

In [22]:

from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      0.90      0.90        10
 Iris-virginica       0.90      0.90      0.90        10

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

In [23]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create the Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
rf_model.fit(X_train, y_train)

# Predict species for test data
rf_pred = rf_model.predict(X_test)

# Calculate accuracy
rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest accuracy:", rf_accuracy)
print("Accuracy percentage:", rf_accuracy * 100, "%")

Random Forest accuracy: 0.9
Accuracy percentage: 90.0 %

In [25]:

import joblib

joblib.dump(model, "iris_decision_tree.pkl")
joblib.dump(rf_model, "iris_random_forest.pkl")

print("Both models saved successfully!")

Both models saved successfully!

In [26]:

from google.colab import files

files.download("iris_decision_tree.pkl")

In [27]:
from google.colab import files files.download("iris_decision_tree.pkl")

In [28]:

from google.colab import files

files.download("iris_random_forest.pkl")

In [29]:

# Display the first 5 rows
print(df.head())

# Check rows and columns
print("\nDataset shape:")
print(df.shape)

# Check column names and data types
print("\nDataset information:")
df.info()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Dataset shape:
(150, 5)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [30]:

print(df.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [33]:

# 1. Make a copy of the original dataset
df_clean = df.copy()

# 2. Remove duplicate rows, if any
df_clean = df_clean.drop_duplicates()

# 3. Display the updated dataset information
print("Dataset shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows remaining:", df_clean.duplicated().sum())

Dataset shape: (147, 5)

Missing values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Duplicate rows remaining: 0

In [34]:

print(df_clean["species"].value_counts())
print("\nClass proportions:")
print(df_clean["species"].value_counts(normalize=True).round(3))

species
Iris-versicolor    50
Iris-virginica     49
Iris-setosa        48
Name: count, dtype: int64

Class proportions:
species
Iris-versicolor    0.340
Iris-virginica     0.333
Iris-setosa        0.327
Name: proportion, dtype: float64

In [35]:

from sklearn.model_selection import train_test_split

# Separate features and target
X_clean = df_clean.drop("species", axis=1)
y_clean = df_clean["species"]

# Split the cleaned dataset
X_train_clean, X_test_clean, y_train_clean, y_test_clean = train_test_split(
    X_clean,
    y_clean,
    test_size=0.2,
    random_state=42,
    stratify=y_clean
)

print("Training features:", X_train_clean.shape)
print("Testing features:", X_test_clean.shape)
print("Training labels:", y_train_clean.shape)
print("Testing labels:", y_test_clean.shape)

Training features: (117, 4)
Testing features: (30, 4)
Training labels: (117,)
Testing labels: (30,)

In [36]:

from sklearn.preprocessing import StandardScaler

# Create the scaler
scaler = StandardScaler()

# Learn scaling parameters from training data only
X_train_scaled = scaler.fit_transform(X_train_clean)

# Apply the same scaling to testing data
X_test_scaled = scaler.transform(X_test_clean)

print("Original training data:")
print(X_train_clean.head())

print("\nScaled training data:")
print(X_train_scaled[:5])

Original training data:
     sepal_length  sepal_width  petal_length  petal_width
67            5.8          2.7           4.1          1.0
90            5.5          2.6           4.4          1.2
103           6.3          2.9           5.6          1.8
52            6.9          3.1           4.9          1.5
129           7.2          3.0           5.8          1.6

Scaled training data:
[[-0.04095301 -0.7435543   0.17925687 -0.27993146]
 [-0.39155076 -0.96777042  0.34976951 -0.01580258]
 [ 0.54337656 -0.29512207  1.03182005  0.77658405]
 [ 1.24457205  0.15331017  0.63395723  0.38039073]
 [ 1.5951698  -0.07090595  1.14549514  0.51245517]]

In [37]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train using scaled training data
knn_model.fit(X_train_scaled, y_train_clean)

# Predict using scaled test data
knn_pred = knn_model.predict(X_test_scaled)

# Calculate accuracy
knn_accuracy = accuracy_score(y_test_clean, knn_pred)

print("KNN accuracy:", knn_accuracy)
print("Accuracy percentage:", knn_accuracy * 100, "%")

KNN accuracy: 0.9333333333333333
Accuracy percentage: 93.33333333333333 %

In [38]:

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Create a pipeline: scaling followed by KNN
knn_pipeline = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier(n_neighbors=5)
)

# Perform 5-fold cross-validation
scores = cross_val_score(
    knn_pipeline,
    X_clean,
    y_clean,
    cv=5,
    scoring="accuracy"
)

print("Accuracy in each fold:", scores)
print("Mean accuracy:", scores.mean())
print("Mean accuracy percentage:", scores.mean() * 100, "%")

Accuracy in each fold: [0.96666667 0.96666667 0.93103448 0.93103448 1.        ]
Mean accuracy: 0.9590804597701149
Mean accuracy percentage: 95.9080459770115 %

In [31]:

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 3

In [32]:

print(df["species"].value_counts())

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [24]:

print("Decision Tree:", accuracy * 100, "%")
print("Random Forest:", rf_accuracy * 100, "%")

Decision Tree: 93.33333333333333 %
Random Forest: 90.0 %

In [14]:
X = df.drop("Species", axis=1)

print(X.head())

KeyError: "['Species'] not found in axis"

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower() == "iris.csv":
            print(os.path.join(root, file))

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower() == "iris.csv":
            print(os.path.join(root, file))

In [ ]:
df = pd.read_csv("df = pd.read_csv(")

NameError: name 'pd' is not defined

In [ ]:
df = pd.read_csv("/kaggle/IRIS.csv")

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd
import os

print("Pandas is ready!")

Pandas is ready!

In [ ]:
for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower() == "iris.csv":
            print(os.path.join(root, file))

In [ ]:
df = pd.read_csv("/content/IRIS.csv")
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/IRIS.csv'

In [ ]:
df = pd.read_csv("/kaggle/IRIS.csv")

In [ ]:
df = pd.read_csv("/content/IRIS.csv")
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/IRIS.csv'

In [ ]:
import os

print("Current directory:", os.getcwd())
print("\nFiles in /content:")

print(os.listdir("/content"))

Current directory: /content

Files in /content:
['.config', 'drive', 'sample_data']

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for filename in files:
        if "iris" in filename.lower():
            print("Found:", os.path.join(root, filename))

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/IRIS.csv")
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/IRIS.csv'

In [ ]:
import pandas as pd



df = pd.read_csv("/content//kaggle/IRIS.csv")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content//kaggle/IRIS.csv'

In [ ]:
temperature = [round(random.uniform(10, 40), 1) for _ in range(1000)]
humidity = [round(random.uniform(30, 90), 1) for _ in range(1000)]

In [ ]:
target_state = []

for temp, hum in zip(temperature, humidity):

    if temp > 28 and hum > 60:
        target_state.append(1)

    elif temp < 18:
        target_state.append(2)

    else:
        target_state.append(0)

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

data = {
    "Temperature": [25, 30, 18, 35, 22],
    "Humidity": [50, 70, 40, 80, 55],
    "AC": [0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)

print(df)

   Temperature  Humidity  AC
0           25        50   0
1           30        70   1
2           18        40   0
3           35        80   1
4           22        55   0

In [ ]:
df.isnull().sum()

Temperature    0
Humidity       0
AC             0
dtype: int64

In [ ]:
data = {
    "Temperature": [25, 30, 18, 35, 22, 31, 16, 27, 33, 20],
    "Humidity": [50, 70, 40, 80, 55, 75, 35, 60, 78, 45],
    "AC": [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]
}

df = pd.DataFrame(data)

print(df)

   Temperature  Humidity  AC
0           25        50   0
1           30        70   1
2           18        40   0
3           35        80   1
4           22        55   0
5           31        75   1
6           16        35   0
7           27        60   1
8           33        78   1
9           20        45   0

In [ ]:
df.shape

(10, 3)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/IRIS.csv")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/IRIS.csv'

In [ ]:
import pandas as pd

df = pd.read_csv("/content/IRIS.csv")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/IRIS.csv'

In [ ]:
import pandas as pd

df = pd.read_csv("/content/IRIS.csv")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/IRIS.csv'

In [ ]:
data = pd.DataFrame({
    "Temperature": temperature,
    "Humidity": humidity,
    "Target_State": target_state
})

data.head()

   Temperature  Humidity  Target_State
0         11.6      43.9             2
1         39.0      67.6             1
2         38.1      55.4             0
3         38.1      67.3             1
4         16.4      65.0             2

In [ ]:
print("Number of rows:", len(data))

Number of rows: 1000

In [ ]:
data.to_csv("climate_data.csv", index=False)

print("climate_data.csv created successfully!")

climate_data.csv created successfully!

In [ ]:
import pandas as pd
import random

# Generate 1,000 synthetic readings
temperature = [round(random.uniform(10, 40), 1) for _ in range(1000)]
humidity = [round(random.uniform(30, 90), 1) for _ in range(1000)]

# Apply business logic
target_state = []

for temp, hum in zip(temperature, humidity):

    if temp > 28 and hum > 60:
        target_state.append(1)

    elif temp < 18:
        target_state.append(2)

    else:
        target_state.append(0)

# Create DataFrame
data = pd.DataFrame({
    "Temperature": temperature,
    "Humidity": humidity,
    "Target_State": target_state
})

# Display first 10 rows
print(data.head(10))

# Check number of rows
print("\nNumber of rows:", len(data))

# Check target states
print("\nTarget State counts:")
print(data["Target_State"].value_counts())

# Save as CSV
data.to_csv("climate_data.csv", index=False)

print("\nclimate_data.csv created successfully!")

   Temperature  Humidity  Target_State
0         11.8      35.0             2
1         20.8      62.8             0
2         24.2      82.1             0
3         33.6      65.4             1
4         38.2      88.5             1
5         34.9      71.2             1
6         18.2      77.9             0
7         37.4      45.2             0
8         23.0      37.7             0
9         16.7      88.1             2

Number of rows: 1000

Target State counts:
Target_State
0    525
2    274
1    201
Name: count, dtype: int64

climate_data.csv created successfully!

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [ ]:
data = pd.read_csv("climate_data.csv")

print(data.head())
print("\nDataset shape:", data.shape)

   Temperature  Humidity  Target_State
0         11.8      35.0             2
1         20.8      62.8             0
2         24.2      82.1             0
3         33.6      65.4             1
4         38.2      88.5             1

Dataset shape: (1000, 3)

In [ ]:
X = data[["Temperature", "Humidity"]]
y = data["Target_State"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = DecisionTreeClassifier(max_depth=4, random_state=42)

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [ ]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 1.0

In [ ]:
test_data = pd.DataFrame({
    "Temperature": [32],
    "Humidity": [70]
})

print("Prediction:", model.predict(test_data)[0])

Prediction: 1

In [ ]:
test_data = pd.DataFrame({
    "Temperature": [15],
    "Humidity": [50]
})

print("Prediction:", model.predict(test_data)[0])

Prediction: 2

In [ ]:
test_data = pd.DataFrame({
    "Temperature": [24],
    "Humidity": [50]
})

print("Prediction:", model.predict(test_data)[0])

Prediction: 0

In [ ]:
import joblib

joblib.dump(model, "climate_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
import os

print(os.path.exists("climate_model.pkl"))

True

In [ ]:
!pip install m2cgen

Collecting m2cgen
  Downloading m2cgen-0.10.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from m2cgen) (2.1.3)
Downloading m2cgen-0.10.0-py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.2/92.2 kB 3.4 MB/s eta 0:00:00
Installing collected packages: m2cgen
Successfully installed m2cgen-0.10.0

In [ ]:
import joblib

model = joblib.load("climate_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [ ]:
import m2cgen as m2c

In [ ]:
raw_c_code = m2c.export_to_c(model)

print(raw_c_code[:1000])

#include <string.h>
void score(double * input, double * output) {
    double var0[3];
    if (input[0] <= 17.949999809265137) {
        memcpy(var0, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
    } else {
        if (input[1] <= 60.0) {
            memcpy(var0, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        } else {
            if (input[0] <= 28.050000190734863) {
                memcpy(var0, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                memcpy(var0, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    memcpy(output, var0, 3 * sizeof(double));
}

In [ ]:
header_content = f"""#ifndef MODEL_H
#define MODEL_H

// Auto-generated TinyML Rules via m2cgen
// Inputs: [0] = Temperature, [1] = Humidity
// Output: Class 0 = Off, Class 1 = AC, Class 2 = Heater

{raw_c_code}

int predict_state(double temperature, double humidity) {{
    double input_data[2] = {{ temperature, humidity }};
    double* scores = score(input_data);

    int class_decision = 0;
    double max_score = scores[0];

    for (int i = 1; i < 3; i++) {{
        if (scores[i] > max_score) {{
            max_score = scores[i];
            class_decision = i;
        }}
    }}

    return class_decision;
}}

#endif
"""

In [ ]:
with open("model.h", "w") as f:
    f.write(header_content)

print("model.h created successfully!")

model.h created successfully!

In [ ]:
tests = pd.DataFrame({
    "Temperature": [32, 15, 24],
    "Humidity": [70, 50, 50]
})

predictions = model.predict(tests)

print(predictions)

[1 2 0]

df.head()

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

data = {
    "Temperature": [25, 30, 18, 35, 22],
    "Humidity": [50, 70, 40, 80, 55],
    "AC": [0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)

print(df)

   Temperature  Humidity  AC
0           25        50   0
1           30        70   1
2           18        40   0
3           35        80   1
4           22        55   0

In [ ]:
df.head()

   Temperature  Humidity  AC
0           25        50   0
1           30        70   1
2           18        40   0
3           35        80   1
4           22        55   0

In [ ]:
df.shape

(5, 3)

In [ ]:
df.columns

Index(['Temperature', 'Humidity', 'AC'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  5 non-null      int64
 1   Humidity     5 non-null      int64
 2   AC           5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df.tail()

   Temperature  Humidity  AC
0           25        50   0
1           30        70   1
2           18        40   0
3           35        80   1
4           22        55   0

In [ ]:
df.describe()

       Temperature   Humidity        AC
count     5.000000   5.000000  5.000000
mean     26.000000  59.000000  0.400000
std       6.670832  15.968719  0.547723
min      18.000000  40.000000  0.000000
25%      22.000000  50.000000  0.000000
50%      25.000000  55.000000  0.000000
75%      30.000000  70.000000  1.000000
max      35.000000  80.000000  1.000000